### PR TITLE
more real gettext based on #28

### PR DESCRIPTION
**Pull request by Dexus**
This PR extends #28 to load automatic the new _MO_ file when we change the locale or domain.

Its also includes a options to #23 

``` js
var options = {
  nonExistingStringCallback: function(locale, domain, msgctxt, msgid){
    console.log("for locale ("+locale+") and domain("+ domain+") are a missing translation with msgctxt ("+msgctxt+") and msgid ("+msgid+")");
  },
}
var gt = Gettext(options);
```

### CODE REVIEW

**Comment by alexanderwallin** [comment]
Thanks for submitting, @Dexus! Let's see what happens in #28 before addressing this one. :)

**Comment by Dexus** [comment]
YW @alexanderwallin 
I don't miss the autoload of the new locale/domain if it is set with config for the loader. I know now one point i do not match yet... dpgettext, dgettext, dpngettext there where domains are set on gettext functions... But that i will fix tomorrow. 

Von meinem iPhone gesendet

**Comment by Dexus** [comment]
@alexanderwallin so now it should work like gettext with php (without the same structure and functions)

**Comment by ArmorDarks** [comment]
I follow up on proposal to wait till #28 will be solved,

**Comment by Dexus** [comment]
@alexanderwallin, @ArmorDarks so it will never solved and i should now make my own fork to go ahead? Or would we work together to make gettext here on a correct way?

Make your decision now, and don't wait until other take the decision...

**Comment by alexanderwallin** [comment]
Hi @Dexus. I'm sorry to have you waiting in vain.

I think the domain/language issue should definitely be addressed here as soon as possible. I also think I can confidently say I will not merge any logic around (automatically) loading resources from disk, since this is not possible or relevant in the browser, and because I regard it as API sugar.

That said, there could definitely be extensions/enhancers/middleware for easily setting up this kind of stuff, especially with a standard gettext folder structure.

I'm closing this. I hope you come up with something nice!

**Pull request closed without merging**
